markdown: kramdown
highlighter: pygments
permalink: blog/:categories/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: Jinliang's Blog                                                # 博客名称
    description: Stay hungry, stay foolish.                                        # 博客描述
    title: Jinliang's Blog                                              # 网页标题
    url: http://zhujinliang.cn                                                # 博客地址
    duoshuo: 11628699                                            # 多说ID
    tongji: 99021da84376c11c97c81c89445ed1d5                                             # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name: Jinliang                                               # 作者名称
    email: jl_zhu(at)foxmail.com                                              # 邮箱地址
    weibo: http://weibo.com/946884579                                               # 微博地址
    github: https://github.com/zhujinliang                                             # GitHub地址
    logo: http://zhujinliang.qiniudn.com/img/avatar/kenan.jpeg                                               # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key