# Basic
title: Jinliang's Blog
subtitle: Welcome~
description: Stay hungry, stay foolish.
# 头像里面的标题
avatarTitle: jinliang
# 头像里面的描述
avatarDesc: 
url: "http://zhujinliang.cn"

# Comment
comment:
    duoshuo: zhujinliang

# Social
social:
    weibo: 946884579 
    github: zhujinliang
    mail: jl_zhu(at)foxmail.com

# 百度统计 
baidu:
    id: eec9579ebee4baa4934db634048cacdd


permalink: blog/:categories/:year/:month/:day/:title.html
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


